theme: jekyll-theme-minimal
# previoulsy called the internet of energy
title: THEMIS datasets
description: data as a fluid
root: smartgrid
url: http://alexandrecuer.github.io/smartgrid
markdown: kramdown
