theme: jekyll-theme-minimal
# previoulsy called the internet of energy
title: THEMIS datasets
description: temperature, humidity and energy recordings on various buildings
root: smartgrid
url: http://alexandrecuer.github.io/smartgrid
markdown: kramdown
logo: industry.svg
