theme: jekyll-theme-minimal
# previoulsy called the internet of energy
title: FREE datasets for datascientists
description: data as a fluid
root: smartgrid
url: http://alexandrecuer.github.io/smartgrid
markdown: kramdown
